import { useEffect, useState } from "react";
import API from "../services/api";

function Reports() {

  const [reports, setReports] = useState([]);

  const [form, setForm] = useState({
    generated_by: "",
    report_type: "Monitoring",
    report_content: ""
  });

  const [editId, setEditId] = useState(null);

  // FETCH
  const fetchReports = () => {
    API.get("/reports")
      .then(res => setReports(res.data))
      .catch(err => console.log(err));
  };

  useEffect(() => {
    fetchReports();
  }, []);

  // INPUT
  const handleChange = (e) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value
    });
  };

  // RESET
  const resetForm = () => {
    setForm({
      generated_by: "",
      report_type: "Monitoring",
      report_content: ""
    });

    setEditId(null);
  };

  // SUBMIT
  const handleSubmit = (e) => {
    e.preventDefault();

    if (editId) {
      API.put(`/reports/${editId}`, {
        report_type: form.report_type,
        report_content: form.report_content
      })
        .then(() => {
          fetchReports();
          resetForm();
        });
    } else {
      API.post("/reports", form)
        .then(() => {
          fetchReports();
          resetForm();
        });
    }
  };

  // DELETE
  const deleteReport = (id) => {
    API.delete(`/reports/${id}`)
      .then(() => fetchReports());
  };

  // EDIT
  const handleEdit = (r) => {
    setForm({
      generated_by: r.generated_by,
      report_type: r.report_type,
      report_content: r.report_content
    });

    setEditId(r.id);
  };

  // TYPE COLOR SYSTEM
  const getTypeColor = (type) => {

    switch (type) {

      case "Monitoring":
        return "#1B5E20";

      case "Evaluation":
        return "#5D4037";

      case "Compliance":
        return "#C9A227";

      default:
        return "#2E2E2E";

    }

  };

  return (

    <div style={styles.container}>

      {/* HEADER */}
      <div style={styles.header}>

        <h1 style={styles.title}>Reports & Intelligence Center</h1>

        <p style={styles.subtitle}>
          Automated monitoring reports, evaluation summaries, and compliance documentation under ARS 1000.
        </p>

      </div>

      {/* FORM */}
      <div style={styles.card}>

        <h3 style={styles.sectionTitle}>
          {editId ? "Edit Report" : "Generate New Report"}
        </h3>

        <form onSubmit={handleSubmit} style={styles.form}>

          <input
            type="number"
            name="generated_by"
            value={form.generated_by}
            onChange={handleChange}
            placeholder="User ID"
            style={styles.input}
            required
          />

          <select
            name="report_type"
            value={form.report_type}
            onChange={handleChange}
            style={styles.input}
          >
            <option value="Monitoring">Monitoring Report</option>
            <option value="Evaluation">Evaluation Report</option>
            <option value="Compliance">Compliance Report</option>
          </select>

          <textarea
            name="report_content"
            value={form.report_content}
            onChange={handleChange}
            placeholder="Write structured report content..."
            rows="4"
            style={styles.textarea}
          />

          <button style={styles.submitBtn}>
            {editId ? "Update Report" : "Generate Report"}
          </button>

        </form>

      </div>

      {/* REPORT GRID */}
      <div style={styles.card}>

        <h3 style={styles.sectionTitle}>Generated Reports</h3>

        <div style={styles.grid}>

          {reports.map((r) => (

            <div key={r.id} style={styles.reportCard}>

              {/* TYPE BADGE */}
              <div
                style={{
                  ...styles.badge,
                  background: getTypeColor(r.report_type)
                }}
              >
                {r.report_type}
              </div>

              {/* META */}
              <p style={styles.meta}>
                Generated by User #{r.generated_by}
              </p>

              <p style={styles.meta}>
                Created:
                {" "}
                {new Date(r.created_at).toLocaleDateString()}
              </p>

              {/* CONTENT */}
              <p style={styles.content}>
                {r.report_content.length > 160
                  ? r.report_content.substring(0, 160) + "..."
                  : r.report_content}
              </p>

              {/* ACTIONS */}
              <div style={styles.actions}>

                <button
                  onClick={() => handleEdit(r)}
                  style={styles.editBtn}
                >
                  Edit
                </button>

                <button
                  onClick={() => deleteReport(r.id)}
                  style={styles.deleteBtn}
                >
                  Delete
                </button>

              </div>

            </div>

          ))}

        </div>

      </div>

    </div>

  );
}

const styles = {

  container: {
    padding: "10px"
  },

  header: {
    marginBottom: "25px"
  },

  title: {
    fontSize: "32px",
    color: "#1E1E1E",
    marginBottom: "8px"
  },

  subtitle: {
    color: "#777",
    fontSize: "15px"
  },

  card: {
    background: "white",
    padding: "25px",
    borderRadius: "18px",
    boxShadow: "0 4px 15px rgba(0,0,0,0.05)",
    marginBottom: "25px"
  },

  sectionTitle: {
    marginBottom: "15px",
    borderBottom: "1px solid #EEE",
    paddingBottom: "10px"
  },

  form: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "12px"
  },

  input: {
    padding: "12px",
    borderRadius: "10px",
    border: "1px solid #DDD",
    background: "#FAFAFA"
  },

  textarea: {
    padding: "12px",
    borderRadius: "10px",
    border: "1px solid #DDD",
    background: "#FAFAFA",
    resize: "none"
  },

  submitBtn: {
    background: "#2E2E2E",
    color: "white",
    border: "none",
    padding: "14px",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600"
  },

  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: "15px"
  },

  reportCard: {
    borderLeft: "4px solid #C9A227",
    padding: "15px",
    borderRadius: "12px",
    background: "#FAFAFA",
    transition: "0.3s ease"
  },

  badge: {
    display: "inline-block",
    padding: "5px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    color: "white",
    marginBottom: "10px",
    fontWeight: "600"
  },

  meta: {
    fontSize: "12px",
    color: "#666"
  },

  content: {
    fontSize: "13px",
    color: "#333",
    marginTop: "8px",
    marginBottom: "10px"
  },

  actions: {
    display: "flex",
    gap: "10px"
  },

  editBtn: {
    background: "#C9A227",
    border: "none",
    padding: "6px 10px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "12px"
  },

  deleteBtn: {
    background: "#C62828",
    color: "white",
    border: "none",
    padding: "6px 10px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "12px"
  }

};

export default Reports;